const STORAGE_PREFIX = "PATATES-STORAGE-";
const MODE = STORAGE_PREFIX + "radio";
const DISABLED_STREAMERS = STORAGE_PREFIX + "disabled";
const ONLY_WATCH_STREAMERS = STORAGE_PREFIX + "only-watch";
const SKIP_INTRO = STORAGE_PREFIX + "intro";
const SKIP_OUTRO = STORAGE_PREFIX + "outro";

const INFORM = STORAGE_PREFIX + "inform";
const LOG = STORAGE_PREFIX + "log";
const WARN = STORAGE_PREFIX + "warn";

const STORAGE_KEY = {
	MODE,
	DISABLED_STREAMERS,
	ONLY_WATCH_STREAMERS,
	SKIP_INTRO,
	SKIP_OUTRO,
};

const LOG_KEY = {
	LOG,
	WARN,
	INFORM,
};
