const STORAGE_PREFIX = "PATATES-STORAGE-";
const RADIO = STORAGE_PREFIX + "radio";
const DISABLED_STREAMERS = STORAGE_PREFIX + "disabled";
const ONLY_WATCH_STREAMERS = STORAGE_PREFIX + "only-watch";
const SKIP_INTRO = STORAGE_PREFIX + "intro";
const SKIP_OUTRO = STORAGE_PREFIX + "outro";

const STORAGE_KEY = {
  RADIO,
  DISABLED_STREAMERS,
  ONLY_WATCH_STREAMERS,
  SKIP_INTRO,
  SKIP_OUTRO,
};

export default STORAGE_KEY;
